//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudOpsPrac.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class emp_table
    {
        public int ID { get; set; }

        [Required(ErrorMessage ="Require")]
        public string empName { get; set; }

        [Required(ErrorMessage = "Require")]
        public string empFname { get; set; }

        [Required(ErrorMessage = "Require")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Require")]
        [MinLength(10,ErrorMessage ="Mobile number should be 10 digits")]
        public string Mobile_Phone { get; set; }

        public string Description { get; set; }
    }
}
